package cn.chuanwise.kotlinsuspendprojection.annotations

/** Descriptive metadata for declarations generated by Kotlin Suspend Projection. */
@Target(AnnotationTarget.CLASS, AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
public annotation class SuspendProjectionMeta(
    val schemaVersion: Int,
    val generatedCodeVersion: Int,
    val generatorVersion: String,
    val origin: String,
    val projection: String,
    val direction: String,
    val lineage: String = "",
    val flags: Int = 0,
    val cancellationCapability: String = SuspendProjectionMetadata.CANCELLATION_UNSPECIFIED,
)

/** Stable values used when encoding [SuspendProjectionMeta]. */
public object SuspendProjectionMetadata {
    public const val SCHEMA_VERSION: Int = 1

    public const val DIRECTION_EXPORTS: String = "exports"
    public const val DIRECTION_IMPORTS: String = "imports"

    public const val CANCELLATION_UNSPECIFIED: String = "unspecified"
    public const val CANCELLATION_NONE: String = "none"
    public const val CANCELLATION_WAITER_INTERRUPTION_ONLY: String =
        "waiter-interruption-only"
    public const val CANCELLATION_COMPLETION_CALLBACK: String = "completion-callback"
    public const val CANCELLATION_FUTURE_GET: String = "future-get"
}
